Shallow copy and deep copy

In [1]:
import pandas as pd
import numpy as np

In [3]:
arr=np.array([[1,3],[4,5]])

In [5]:
arr

array([[1, 3],
       [4, 5]])

In [7]:
a=arr  #shallow copy

In [9]:
b=np.copy(arr)  #deep copy

In [11]:
arr[0]

array([1, 3])

In [13]:
arr[0][0]

1

In [15]:
arr[0][0] = 76

In [17]:
arr

array([[76,  3],
       [ 4,  5]])

In [19]:
a

#reflect new value

array([[76,  3],
       [ 4,  5]])

In [21]:
b

#getting the new value
#new value are not reflected

array([[1, 3],
       [4, 5]])

In [23]:
arr[0:1]

array([[76,  3]])

In [25]:
np.fromfunction(lambda i,j : i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [27]:
np.fromfunction(lambda i,j : i*j , [3,3])  #it gives the float numbers

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [29]:
np.fromfunction(lambda i,j : i*j , [3,3] , dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [31]:
l=[3,4,5,6,7,8]

In [33]:
arr1=np.array(l)

In [35]:
arr1

array([3, 4, 5, 6, 7, 8])

In [37]:
arr2=np.array([[2,3,4,5],[6,7,8,9],[3,4,5,6]])

In [39]:
arr2

array([[2, 3, 4, 5],
       [6, 7, 8, 9],
       [3, 4, 5, 6]])

In [41]:
type(arr2)

numpy.ndarray

In [43]:
arr2.ndim

2

In [45]:
arr1.size

6

In [47]:
arr2.size

12

In [49]:
range(0,6)

range(0, 6)

In [51]:
list(range(0,6))

[0, 1, 2, 3, 4, 5]

In [53]:
np.arange(6.6)

array([0., 1., 2., 3., 4., 5., 6.])

In [55]:
np.arange(5.6,9.8,0.3)

array([5.6, 5.9, 6.2, 6.5, 6.8, 7.1, 7.4, 7.7, 8. , 8.3, 8.6, 8.9, 9.2,
       9.5, 9.8])

In [57]:
np.arange(6.6,2.0,-0.3)

array([6.6, 6.3, 6. , 5.7, 5.4, 5.1, 4.8, 4.5, 4.2, 3.9, 3.6, 3.3, 3. ,
       2.7, 2.4, 2.1])

In [59]:
np.linspace(5,9,5)

array([5., 6., 7., 8., 9.])

In [61]:
np.linspace(1.1,1.3,num=19)

array([1.1       , 1.11111111, 1.12222222, 1.13333333, 1.14444444,
       1.15555556, 1.16666667, 1.17777778, 1.18888889, 1.2       ,
       1.21111111, 1.22222222, 1.23333333, 1.24444444, 1.25555556,
       1.26666667, 1.27777778, 1.28888889, 1.3       ])

In [63]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [65]:
np.zeros((3,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [67]:
np.ones([3,4,5])

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [69]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [71]:
np.ones([3,4],dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [73]:
np.ones(3,dtype=int)*2

array([2, 2, 2])

In [75]:
np.logspace(2,3,4)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

Random data generation

In [79]:
np.random.rand(4)

#this data is generated from gaussion distribution

array([0.72712456, 0.34365529, 0.6128191 , 0.54438078])

In [81]:
np.random.randn(2,3) 

#ganerated by standard distribution

array([[-0.51687661, -2.04521335,  0.50118591],
       [-1.21000548, -0.16651648,  0.26438955]])

In [83]:
np.random.randn(2,3,4)

array([[[ 1.12063159,  0.13657065,  0.93312461, -1.1276434 ],
        [-1.25160524, -1.01450967, -0.63501956, -1.24424142],
        [-0.72458647,  0.42670825, -2.67314257,  0.59365536]],

       [[-1.06059548, -1.57469275, -0.36018932, -0.52010108],
        [ 0.72983201, -0.29276887, -0.79492628, -2.07525125],
        [-1.96107036, -0.32840703, -1.03091677, -0.59248954]]])

In [85]:
np.random.randint(3,20)

14

In [87]:
arr = np.random.randint(4,20,(3,4))

In [89]:
np.random.randint(3,90,(2,4,5))

array([[[24, 49, 16, 35, 11],
        [14, 54, 67, 12,  3],
        [84, 80, 65, 69, 40],
        [33, 75, 80, 24, 32]],

       [[88, 68, 11, 77, 22],
        [42, 35, 19, 71, 22],
        [36, 43, 56, 26, 18],
        [35, 79, 59,  4, 24]]])

In [91]:
arr

array([[ 5,  6,  7, 18],
       [ 8, 11,  9,  4],
       [13, 13, 11,  9]])

In [93]:
arr.max()

18

In [95]:
arr.min()

4

In [97]:
np.std(arr)

3.7969285832981723

In [99]:
np.mean(arr)

9.5

In [101]:
arr>10

array([[False, False, False,  True],
       [False,  True, False, False],
       [ True,  True,  True, False]])

In [103]:
arr[arr>10]

array([18, 11, 13, 13, 11])

In [105]:
type(arr)

numpy.ndarray

In [107]:
arr

array([[ 5,  6,  7, 18],
       [ 8, 11,  9,  4],
       [13, 13, 11,  9]])

In [109]:
arr*arr

array([[ 25,  36,  49, 324],
       [ 64, 121,  81,  16],
       [169, 169, 121,  81]])

In [113]:
pd.DataFrame(np.random.randn(10,4))

0         1         2         3
0  0.956426  1.749003  0.520800 -0.414106
1  0.855832  0.315427 -0.377050 -0.771358
2  2.014199  1.122951 -0.349928 -2.696153
3  0.811915  0.675797 -1.052574  1.959004
4 -0.850264  0.222132 -0.169510 -0.720877
5  0.052900  1.639893 -1.106544 -0.441649
6 -1.349622  2.142444  0.787771  0.357461
7  0.886892  1.626593  1.220329 -0.936803
8  0.728887 -2.884459  0.270117 -0.881483
9  0.065868  1.387196 -0.530784  0.308127

In [115]:
pd.DataFrame(np.random.randn(10,4),index=pd.date_range('2025-05-07',periods=10))

0         1         2         3
2025-05-07 -0.199583 -0.978781  1.129252  0.860001
2025-05-08  0.249780  1.036024 -1.058378  0.656211
2025-05-09 -1.263324 -0.614578 -1.779367  2.426250
2025-05-10  0.226564 -0.787219  1.854702 -0.804366
2025-05-11  0.573566  1.343805 -0.541121  0.057905
2025-05-12 -0.257445  2.081391 -0.023022  0.387780
2025-05-13 -0.373639  0.056849  0.881740 -1.293548
2025-05-14 -1.318205  2.167360 -1.717832  0.864061
2025-05-15 -1.234134  0.362490 -0.837318  1.066727
2025-05-16 -2.116733  0.328336  0.558643  1.521294

In [231]:
df = pd.DataFrame(np.random.randn(10,4),index=pd.date_range('2025-05-07',periods=10),columns=['a','b','c','d'])

In [233]:
df

a         b         c         d
2025-05-07  0.402116 -0.384290 -0.368267  0.275474
2025-05-08 -0.854607 -0.268929  0.318291  0.171250
2025-05-09  0.585964 -0.245530 -0.652331  0.189790
2025-05-10 -0.736026  0.828320  0.024691  0.306254
2025-05-11  1.807951  0.754465 -0.938972  1.912790
2025-05-12 -0.323966  0.523374  0.337510 -0.038787
2025-05-13  0.093659  0.766627 -0.053891 -0.456875
2025-05-14  0.272634  1.602550 -0.185592 -1.166650
2025-05-15 -0.213006  0.834138  0.459209  0.638330
2025-05-16 -2.747052 -0.206302 -0.526626 -0.785678

In [235]:
#new column

df['new']=df['c']+df['d']

In [237]:
df

a         b         c         d       new
2025-05-07  0.402116 -0.384290 -0.368267  0.275474 -0.092793
2025-05-08 -0.854607 -0.268929  0.318291  0.171250  0.489541
2025-05-09  0.585964 -0.245530 -0.652331  0.189790 -0.462540
2025-05-10 -0.736026  0.828320  0.024691  0.306254  0.330945
2025-05-11  1.807951  0.754465 -0.938972  1.912790  0.973818
2025-05-12 -0.323966  0.523374  0.337510 -0.038787  0.298723
2025-05-13  0.093659  0.766627 -0.053891 -0.456875 -0.510766
2025-05-14  0.272634  1.602550 -0.185592 -1.166650 -1.352242
2025-05-15 -0.213006  0.834138  0.459209  0.638330  1.097539
2025-05-16 -2.747052 -0.206302 -0.526626 -0.785678 -1.312303

In [239]:
def test(a):
    return a*a

In [241]:
df['squared_col']=df['d'].apply(test)

In [243]:
df

a         b         c         d       new  squared_col
2025-05-07  0.402116 -0.384290 -0.368267  0.275474 -0.092793     0.075886
2025-05-08 -0.854607 -0.268929  0.318291  0.171250  0.489541     0.029327
2025-05-09  0.585964 -0.245530 -0.652331  0.189790 -0.462540     0.036020
2025-05-10 -0.736026  0.828320  0.024691  0.306254  0.330945     0.093792
2025-05-11  1.807951  0.754465 -0.938972  1.912790  0.973818     3.658767
2025-05-12 -0.323966  0.523374  0.337510 -0.038787  0.298723     0.001504
2025-05-13  0.093659  0.766627 -0.053891 -0.456875 -0.510766     0.208734
2025-05-14  0.272634  1.602550 -0.185592 -1.166650 -1.352242     1.361072
2025-05-15 -0.213006  0.834138  0.459209  0.638330  1.097539     0.407465
2025-05-16 -2.747052 -0.206302 -0.526626 -0.785678 -1.312303     0.617289

In [245]:
# Query to create a new column and store the logrethmic values for column d .
# the log values of negitive values and the zeros are not defined so its values become the NaN values

df['log_d']=np.log(df['d'])

C:\Users\chatr\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)


In [247]:
df

a         b         c         d       new  squared_col  \
2025-05-07  0.402116 -0.384290 -0.368267  0.275474 -0.092793     0.075886   
2025-05-08 -0.854607 -0.268929  0.318291  0.171250  0.489541     0.029327   
2025-05-09  0.585964 -0.245530 -0.652331  0.189790 -0.462540     0.036020   
2025-05-10 -0.736026  0.828320  0.024691  0.306254  0.330945     0.093792   
2025-05-11  1.807951  0.754465 -0.938972  1.912790  0.973818     3.658767   
2025-05-12 -0.323966  0.523374  0.337510 -0.038787  0.298723     0.001504   
2025-05-13  0.093659  0.766627 -0.053891 -0.456875 -0.510766     0.208734   
2025-05-14  0.272634  1.602550 -0.185592 -1.166650 -1.352242     1.361072   
2025-05-15 -0.213006  0.834138  0.459209  0.638330  1.097539     0.407465   
2025-05-16 -2.747052 -0.206302 -0.526626 -0.785678 -1.312303     0.617289   

               log_d  
2025-05-07 -1.289262  
2025-05-08 -1.764631  
2025-05-09 -1.661835  
2025-05-10 -1.183339  
2025-05-11  0.648563  
2025-05-12       NaN  
2025-05-13       NaN  
2025-05-14       NaN  
2025-05-15 -0.448900  
2025-05-16       NaN

In [249]:
def test1(a):
    if(a<=0):
        return a
    else:
        return np.log(a)

In [251]:
#Create a new column where negative values of column d should remain same and positive values of column d should get log values.

df['log_d2']=df['d'].apply(test1)

In [253]:
df

a         b         c         d       new  squared_col  \
2025-05-07  0.402116 -0.384290 -0.368267  0.275474 -0.092793     0.075886   
2025-05-08 -0.854607 -0.268929  0.318291  0.171250  0.489541     0.029327   
2025-05-09  0.585964 -0.245530 -0.652331  0.189790 -0.462540     0.036020   
2025-05-10 -0.736026  0.828320  0.024691  0.306254  0.330945     0.093792   
2025-05-11  1.807951  0.754465 -0.938972  1.912790  0.973818     3.658767   
2025-05-12 -0.323966  0.523374  0.337510 -0.038787  0.298723     0.001504   
2025-05-13  0.093659  0.766627 -0.053891 -0.456875 -0.510766     0.208734   
2025-05-14  0.272634  1.602550 -0.185592 -1.166650 -1.352242     1.361072   
2025-05-15 -0.213006  0.834138  0.459209  0.638330  1.097539     0.407465   
2025-05-16 -2.747052 -0.206302 -0.526626 -0.785678 -1.312303     0.617289   

               log_d    log_d2  
2025-05-07 -1.289262 -1.289262  
2025-05-08 -1.764631 -1.764631  
2025-05-09 -1.661835 -1.661835  
2025-05-10 -1.183339 -1.183339  
2025-05-11  0.648563  0.648563  
2025-05-12       NaN -0.038787  
2025-05-13       NaN -0.456875  
2025-05-14       NaN -1.166650  
2025-05-15 -0.448900 -0.448900  
2025-05-16       NaN -0.785678

In [255]:
#create new column by considering column A and return yes if the value is even, return no if the value is not even.

df['a_even'] = df['a'].apply(lambda x: 'yes' if int(x) % 2 == 0 else 'no')


In [257]:
df

a         b         c         d       new  squared_col  \
2025-05-07  0.402116 -0.384290 -0.368267  0.275474 -0.092793     0.075886   
2025-05-08 -0.854607 -0.268929  0.318291  0.171250  0.489541     0.029327   
2025-05-09  0.585964 -0.245530 -0.652331  0.189790 -0.462540     0.036020   
2025-05-10 -0.736026  0.828320  0.024691  0.306254  0.330945     0.093792   
2025-05-11  1.807951  0.754465 -0.938972  1.912790  0.973818     3.658767   
2025-05-12 -0.323966  0.523374  0.337510 -0.038787  0.298723     0.001504   
2025-05-13  0.093659  0.766627 -0.053891 -0.456875 -0.510766     0.208734   
2025-05-14  0.272634  1.602550 -0.185592 -1.166650 -1.352242     1.361072   
2025-05-15 -0.213006  0.834138  0.459209  0.638330  1.097539     0.407465   
2025-05-16 -2.747052 -0.206302 -0.526626 -0.785678 -1.312303     0.617289   

               log_d    log_d2 a_even  
2025-05-07 -1.289262 -1.289262    yes  
2025-05-08 -1.764631 -1.764631    yes  
2025-05-09 -1.661835 -1.661835    yes  
2025-05-10 -1.183339 -1.183339    yes  
2025-05-11  0.648563  0.648563     no  
2025-05-12       NaN -0.038787    yes  
2025-05-13       NaN -0.456875    yes  
2025-05-14       NaN -1.166650    yes  
2025-05-15 -0.448900 -0.448900    yes  
2025-05-16       NaN -0.785678    yes

In [259]:
#Create a new column for the index values

df['YY-MM-DD']=df.index

In [261]:
df

a         b         c         d       new  squared_col  \
2025-05-07  0.402116 -0.384290 -0.368267  0.275474 -0.092793     0.075886   
2025-05-08 -0.854607 -0.268929  0.318291  0.171250  0.489541     0.029327   
2025-05-09  0.585964 -0.245530 -0.652331  0.189790 -0.462540     0.036020   
2025-05-10 -0.736026  0.828320  0.024691  0.306254  0.330945     0.093792   
2025-05-11  1.807951  0.754465 -0.938972  1.912790  0.973818     3.658767   
2025-05-12 -0.323966  0.523374  0.337510 -0.038787  0.298723     0.001504   
2025-05-13  0.093659  0.766627 -0.053891 -0.456875 -0.510766     0.208734   
2025-05-14  0.272634  1.602550 -0.185592 -1.166650 -1.352242     1.361072   
2025-05-15 -0.213006  0.834138  0.459209  0.638330  1.097539     0.407465   
2025-05-16 -2.747052 -0.206302 -0.526626 -0.785678 -1.312303     0.617289   

               log_d    log_d2 a_even   YY-MM-DD  
2025-05-07 -1.289262 -1.289262    yes 2025-05-07  
2025-05-08 -1.764631 -1.764631    yes 2025-05-08  
2025-05-09 -1.661835 -1.661835    yes 2025-05-09  
2025-05-10 -1.183339 -1.183339    yes 2025-05-10  
2025-05-11  0.648563  0.648563     no 2025-05-11  
2025-05-12       NaN -0.038787    yes 2025-05-12  
2025-05-13       NaN -0.456875    yes 2025-05-13  
2025-05-14       NaN -1.166650    yes 2025-05-14  
2025-05-15 -0.448900 -0.448900    yes 2025-05-15  
2025-05-16       NaN -0.785678    yes 2025-05-16

In [263]:
type(df.index)

pandas.core.indexes.datetimes.DatetimeIndex

In [265]:
type(df['YY-MM-DD'])

pandas.core.series.Series

In [267]:
df['YY-MM-DD'].dtype

#  M8 means “datetime64” in numpy 

dtype('<M8[ns]')

In [269]:
# Separate the date into year, month, and day

df['year']=df['YY-MM-DD'].dt.year
df['Month']=df['YY-MM-DD'].dt.month
df['Day']=df['YY-MM-DD'].dt.day

In [271]:
df

a         b         c         d       new  squared_col  \
2025-05-07  0.402116 -0.384290 -0.368267  0.275474 -0.092793     0.075886   
2025-05-08 -0.854607 -0.268929  0.318291  0.171250  0.489541     0.029327   
2025-05-09  0.585964 -0.245530 -0.652331  0.189790 -0.462540     0.036020   
2025-05-10 -0.736026  0.828320  0.024691  0.306254  0.330945     0.093792   
2025-05-11  1.807951  0.754465 -0.938972  1.912790  0.973818     3.658767   
2025-05-12 -0.323966  0.523374  0.337510 -0.038787  0.298723     0.001504   
2025-05-13  0.093659  0.766627 -0.053891 -0.456875 -0.510766     0.208734   
2025-05-14  0.272634  1.602550 -0.185592 -1.166650 -1.352242     1.361072   
2025-05-15 -0.213006  0.834138  0.459209  0.638330  1.097539     0.407465   
2025-05-16 -2.747052 -0.206302 -0.526626 -0.785678 -1.312303     0.617289   

               log_d    log_d2 a_even   YY-MM-DD  year  Month  Day  
2025-05-07 -1.289262 -1.289262    yes 2025-05-07  2025      5    7  
2025-05-08 -1.764631 -1.764631    yes 2025-05-08  2025      5    8  
2025-05-09 -1.661835 -1.661835    yes 2025-05-09  2025      5    9  
2025-05-10 -1.183339 -1.183339    yes 2025-05-10  2025      5   10  
2025-05-11  0.648563  0.648563     no 2025-05-11  2025      5   11  
2025-05-12       NaN -0.038787    yes 2025-05-12  2025      5   12  
2025-05-13       NaN -0.456875    yes 2025-05-13  2025      5   13  
2025-05-14       NaN -1.166650    yes 2025-05-14  2025      5   14  
2025-05-15 -0.448900 -0.448900    yes 2025-05-15  2025      5   15  
2025-05-16       NaN -0.785678    yes 2025-05-16  2025      5   16

In [273]:
#Create a column for day of the week (like Monday, Tuesday)

df['Day_of_week']=df['YY-MM-DD'].dt.day_name()

In [280]:
df

a         b         c         d       new  squared_col  \
2025-05-07  0.402116 -0.384290 -0.368267  0.275474 -0.092793     0.075886   
2025-05-08 -0.854607 -0.268929  0.318291  0.171250  0.489541     0.029327   
2025-05-09  0.585964 -0.245530 -0.652331  0.189790 -0.462540     0.036020   
2025-05-10 -0.736026  0.828320  0.024691  0.306254  0.330945     0.093792   
2025-05-11  1.807951  0.754465 -0.938972  1.912790  0.973818     3.658767   
2025-05-12 -0.323966  0.523374  0.337510 -0.038787  0.298723     0.001504   
2025-05-13  0.093659  0.766627 -0.053891 -0.456875 -0.510766     0.208734   
2025-05-14  0.272634  1.602550 -0.185592 -1.166650 -1.352242     1.361072   
2025-05-15 -0.213006  0.834138  0.459209  0.638330  1.097539     0.407465   
2025-05-16 -2.747052 -0.206302 -0.526626 -0.785678 -1.312303     0.617289   

               log_d    log_d2 a_even   YY-MM-DD  year  Month  Day Day_of_week  
2025-05-07 -1.289262 -1.289262    yes 2025-05-07  2025      5    7   Wednesday  
2025-05-08 -1.764631 -1.764631    yes 2025-05-08  2025      5    8    Thursday  
2025-05-09 -1.661835 -1.661835    yes 2025-05-09  2025      5    9      Friday  
2025-05-10 -1.183339 -1.183339    yes 2025-05-10  2025      5   10    Saturday  
2025-05-11  0.648563  0.648563     no 2025-05-11  2025      5   11      Sunday  
2025-05-12       NaN -0.038787    yes 2025-05-12  2025      5   12      Monday  
2025-05-13       NaN -0.456875    yes 2025-05-13  2025      5   13     Tuesday  
2025-05-14       NaN -1.166650    yes 2025-05-14  2025      5   14   Wednesday  
2025-05-15 -0.448900 -0.448900    yes 2025-05-15  2025      5   15    Thursday  
2025-05-16       NaN -0.785678    yes 2025-05-16  2025      5   16      Friday